biblioteca/urls.py
from django.conf.urls.defaults import *
from django.views.generic import TemplateView, ListView
from biblioteca.forms import *
from biblioteca.models import *

urlpatterns = patterns('biblioteca.views',
    url(r'^test-404$', TemplateView.as_view(template_name="404.html")),

    url(r'^$',          'home'),
    url(r'^ricerca_r$', 'ricerca.ricerca_rapida'),
    url(r'^ricerca$',	'ricerca.ricerca_avanzata'),

    url(r'^edizioni$',                          ListView.as_view(
                                                    queryset=Edizione.objects.order_by('titolo'))),
    url(r'^edizioni/(?P<pk>\d+)$',              'edizione.dettagli'),
    url(r'^edizioni/(?P<pk>\d+)/modifica$',     'edizione.modifica'),
    url(r'^edizioni/(?P<pk>\d+)/elimina$',      'edizione.elimina'),
    url(r'^edizioni/aggiungi$',                 'edizione.aggiungi'),
    url(r'^edizioni/aggiungi/googlebooks',      TemplateView.as_view(
                                                    template_name='biblioteca/googlebooks_import.html')),


    url(r'^copie/(?P<pk>\d+)/\+prestiti$',              'prestiti.copia'),
    url(r'^copie/(?P<pk>\d+)/\+prestiti/aggiungi$',     'prestiti.aggiungi'),

    url(r'^prestiti$',                                  'prestiti.lista'),
    url(r'^prestiti/(?P<pk>\d+)$',                      'prestiti.dettagli'),
    url(r'^prestiti/(?P<pk>\d+)/modifica$',             'prestiti.modifica'),
    url(r'^prestiti/(?P<pk>\d+)/restituisci$',          'prestiti.restituisci'),

    url(r'^armadi$',                            'armadio'),
    url(r'^armadi/(?P<nome_armadio>[\w\d]+)$',  'armadio'),


)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'', include('Biblioteca_IISCurcio.biblioteca.urls')),
)

biblioteca/models.py
from django.db import models

from datetime import date

class Edizione(models.Model):
    titolo          = models.CharField(max_length=900,  db_column='Titolo',         db_index=True)
    casaeditrice    = models.CharField(max_length=135,  db_column='CasaEditrice',   blank=True, verbose_name='Casa editrice', db_index=True)
    anno            = models.CharField(max_length=4,    db_column='Anno',           blank=True, null=True)
    isbn            = models.CharField(max_length=60,   db_column='ISBN',           blank=True, verbose_name='ISBN', db_index=True)

    def clean(self):
	self.titolo = self.titolo.strip()
	self.casaeditrice = self.casaeditrice.strip()

    def __unicode__(self):
        return "#%d: %s" % (self.id, self.titolo)
    class Meta:
        db_table = u'Edizioni'
        verbose_name_plural = 'Edizioni'

class Autore(models.Model):
    nome        = models.CharField(max_length=135, db_column='Nome')
    cognome     = models.CharField(max_length=300, db_column='Cognome', blank=True)
    edizione    = models.ForeignKey(Edizione, db_column='FK_IdEdizione')
    
    def clean(self):
	self.nome = self.nome.strip()
	self.cognome = self.cognome.strip()

    def __unicode__(self):
        return "#%d: %s %s" % (self.id, self.nome, self.cognome)
    class Meta:
        db_table = u'Autori'
        unique_together = ('nome', 'cognome', 'edizione')
        verbose_name_plural = 'Autori'


class Copia(models.Model):
    armadio     = models.CharField(max_length=60, db_column='Armadio')
    scaffale    = models.CharField(max_length=60, db_column='Scaffale')
    posizione   = models.IntegerField(db_column='Posizione')
    note        = models.TextField(db_column='Note', blank=True)
    dataora     = models.DateTimeField(null=True, db_column='DataOra', auto_now_add=True)
    edizione    = models.ForeignKey(Edizione, db_column='FK_idEdizione')

    def __unicode__(self):
        return "#%d: %s %s %d" % (self.id, self.armadio, self.scaffale, self.posizione)
    class Meta:
        db_table = u'Copie'
        unique_together = ('armadio', 'scaffale', 'posizione')
        verbose_name_plural = 'Copie'

    def clean(self):
	self.armadio = self.armadio.strip()
	self.scaffale = self.scaffale.strip()

    def prestito_corrente(self):
        try:
            return self.prestito_set.get(datarestituzione__isnull=True)
        except Prestito.DoesNotExist:
            return None


class Prestito(models.Model):
    nome        = models.CharField(max_length=135, db_column='Nome')
    cognome     = models.CharField(max_length=135, db_column='Cognome')
    categoria   = models.CharField(max_length=60, db_column='Categoria')
    classe      = models.CharField(max_length=30, db_column='Classe', blank=True)

    dataconsegna        = models.DateField(db_column='DataConsegna', auto_now_add=True)
    datarestituzione    = models.DateField(null=True, db_column='DataRestituzione', blank=True)

    nomeresp    = models.CharField(max_length=135, db_column='NomeResp')
    cognomeresp = models.CharField(max_length=135, db_column='CognomeResp')

    note = models.TextField(db_column='Note', blank=True)

    copia = models.ForeignKey(Copia, db_column='FK_idCopia')

    def __unicode__(self):
        return "#%d: %s %s, %s: %s" % (self.id, self.nome, self.cognome, self.dataconsegna, self.copia.edizione.titolo)
    class Meta:
        db_table = u'Prestiti'
        verbose_name_plural = 'Prestiti'

    def durata(self):
        if self.datarestituzione == None:
            return date.today() - self.dataconsegna
        else:
            return self.datarestituzione - self.dataconsegna

biblioteca/forms.py
from django.forms           import *
from django.forms.models    import inlineformset_factory

from biblioteca.models  import * 

class EdizioneForm(ModelForm):
    class Meta:
        model = Edizione

Autori_InlineFormSet = inlineformset_factory(Edizione, Autore, extra=1, can_delete=True)

Copie_InlineFormSet = inlineformset_factory(Edizione, Copia, extra=1, can_delete=True)

class PrestitoForm(ModelForm):
    class Meta:
        model = Prestito

class RicercaPrestitiForm(Form):
    query = CharField(required=False)
    restituiti = BooleanField(required=False)
    order = ChoiceField(required=False, choices=(
                            ('consegna', 'Data consegna'),
                            ('restituzione', 'Data restituzione'),
                            ('beneficiario', 'Cognome/nome'),
                        ))
    

biblioteca/views/edizione.py
from django.http                    import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts               import render_to_response, get_object_or_404
from django.core.context_processors import csrf
from django.template                import RequestContext

from biblioteca.models  import *
from biblioteca.forms   import *

def dettagli(request, pk):
    edizione = get_object_or_404(Edizione, id=pk)
    context_data = {
        'edizione': edizione,
        'autori':   edizione.autore_set.order_by('cognome'),
    }
    return render_to_response('biblioteca/edizione_detail.html', context_data,
            context_instance=RequestContext(request))

def modifica(request, pk):
    edizione = get_object_or_404(Edizione, pk=pk)

    if request.method == 'POST':
        form, fs_autori, fs_copie = \
                EdizioneForm(request.POST, instance=edizione), \
                Autori_InlineFormSet(request.POST, instance=edizione, prefix='autori'), \
                Copie_InlineFormSet(request.POST, instance=edizione, prefix='copie')

        if form.is_valid() and fs_autori.is_valid() and fs_copie.is_valid():
            form.save()
            fs_autori.save()
            fs_copie.save()
            return HttpResponseRedirect('/edizioni/'+pk)
    else:
        autori_queryset = edizione.autore_set.order_by('cognome')

        form, fs_autori, fs_copie = \
                EdizioneForm(instance=edizione), \
                Autori_InlineFormSet(instance=edizione, queryset=autori_queryset, prefix='autori'), \
                Copie_InlineFormSet(instance=edizione, prefix='copie')

    context_data = {
        'object': edizione,
        'form': form,
        'formset_autori': fs_autori,
        'formset_copie': fs_copie,
    }
    return render_to_response('biblioteca/edizione_form.html', context_data,
                                context_instance=RequestContext(request))


def aggiungi(request):
    if request.method == 'POST':
        form = EdizioneForm(request.POST)
        if form.is_valid():
            form.save()
            edizione = form.instance
        else:
            edizione = None

        fs_autori = Autori_InlineFormSet(request.POST, instance=edizione, prefix='autori')
        fs_copie = Copie_InlineFormSet(request.POST, instance=edizione, prefix='copie')
        if edizione and fs_autori.is_valid() and fs_copie.is_valid():
            fs_autori.save()
            fs_copie.save()
            return HttpResponseRedirect('/edizioni/'+str(edizione.id))

    else:
        form = EdizioneForm(initial=request.GET.items())

        # Crea e popola il formset, partendo dai parametri GET. Fa ribrezzo, lo so.
        init_autori = request.GET.getlist('autori')
        Autori_IFS = inlineformset_factory(Edizione, Autore, can_delete=True, \
                                            extra=max(1, len(init_autori)))
        fs_autori = Autori_IFS(prefix='autori')
        for subform, autore in zip(fs_autori.forms, init_autori):
            toks = autore.split(',', 2)
            if len(toks) < 2: toks.append('')
            subform.initial =   { 'nome'   : toks[0]
                                , 'cognome': toks[1] }

        Copie_IFS = inlineformset_factory(Edizione, Copia, can_delete=True, extra=1)
        fs_copie = Copie_IFS(prefix='copie')

    context_data = {
        'form': form,
        'formset_autori': fs_autori,
        'formset_copie': fs_copie,
    }
    return render_to_response('biblioteca/edizione_form.html', context_data,
                                context_instance=RequestContext(request))


def elimina(request, pk):
    if request.method != 'POST':
        return HttpResponseBadRequest()

    edizione = get_object_or_404(Edizione, pk=pk)
    edizione.delete()

    return HttpResponseRedirect('/edizioni')

biblioteca/views/prestiti.py
from django.http                    import HttpResponse, HttpResponseRedirect
from django.shortcuts               import render_to_response, get_object_or_404
from django.forms.models            import inlineformset_factory
from django.forms                   import widgets
from django.template                import RequestContext

from biblioteca.models  import *
from biblioteca.forms   import *
from biblioteca.search  import prestiti_search

import datetime


def lista(request):
    form_ricerca = RicercaPrestitiForm(request.GET)
    
    context_data = { 'form' : form_ricerca }
    if form_ricerca.is_valid():
        search_params = form_ricerca.cleaned_data

        context_data['search'] = len(request.GET) > 0
        prestiti = prestiti_search(form_ricerca.cleaned_data)

        order = search_params['order']
        if order == 'consegna':
            prestiti = prestiti.order_by('-dataconsegna')
        elif order == 'restituzione':
            prestiti = prestiti.order_by('-datarestituzione')
        elif order == 'beneficiario':
            prestiti = prestiti.order_by('cognome', 'nome')
    else:
        prestiti = Prestito.objects.filter(datarestituzione__isnull=True)

    context_data['object_list'] = prestiti

    return render_to_response('biblioteca/prestito_list.html', context_data,
                                context_instance=RequestContext(request))


def dettagli(request, pk):
    prestito = get_object_or_404(Prestito, pk=pk)
    context_data = {
        'mode': 'prestito',
        'prestito': prestito,
        'copia': prestito.copia,
        'prestiti': prestito.copia.prestito_set.filter(datarestituzione__isnull=False).order_by('dataconsegna')
    }
    return render_to_response('biblioteca/prestiti_copia.html', context_data,
                                context_instance=RequestContext(request))


def modifica(request, pk):
    prestito = get_object_or_404(Prestito, pk=pk)
    id_copia = prestito.copia.id
    if request.method == 'POST':
        form_data = request.POST.copy()
        form_data['copia'] = id_copia
        form = PrestitoForm(form_data, instance=prestito)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/copie/%d/+prestiti" % id_copia)
    else:
        form = PrestitoForm(instance=prestito)


    context_data = {
        'form': form,
        'copia': prestito.copia
    }
    return render_to_response('biblioteca/prestito_form.html', context_data,
                                context_instance=RequestContext(request))


# 
# Prestiti relativi a una copia
#
def copia(request, pk):
    copia = get_object_or_404(Copia, pk=pk)
    context_data = {
        'mode': 'copia',
        'prestito': copia.prestito_corrente(),
        'copia': copia,
        'prestiti': copia.prestito_set.filter(datarestituzione__isnull=False).order_by('dataconsegna')
    }
    return render_to_response('biblioteca/prestiti_copia.html', context_data,
                                context_instance=RequestContext(request))


def restituisci(request, pk):
    prestito = get_object_or_404(Prestito, pk=pk)

    if request.method == 'POST':
        prestito.datarestituzione = datetime.datetime.now()
        prestito.save()
        return HttpResponseRedirect('/copie/%d/+prestiti' % prestito.copia.id)


def aggiungi(request, pk):
    copia = get_object_or_404(Copia, pk=pk)

    if request.method == 'POST':
        form_data = request.POST.copy()
        form_data['copia'] = copia.id
        form = PrestitoForm(form_data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/copie/"+pk+"/+prestiti")
    else:
        form = PrestitoForm()

    context_data = {
        'form': form,
        'copia': copia,
    }
    return render_to_response('biblioteca/prestito_form.html', context_data,
                                context_instance=RequestContext(request))

biblioteca/views/ricerca.py
from django.template  import RequestContext
from django.shortcuts import render_to_response
#from django.db        import QuerySet

from biblioteca.search import edizioni_advanced_search, edizioni_simple_search

def ricerca(search_callback, template, request):

    params = request.GET.copy()
    for key, value in params.iteritems():
	if value == '':
	    del params[key]

    queryset = None
    if len(params) > 0:
	queryset = search_callback(params)

    count = 0
    if type(queryset) is 'QuerySet': count = queryset.count()
    elif type(queryset) is list:     count = len(queryset)

    context_data = {
	'done' : (queryset != None),
	'results': queryset,
	'params': params
    }
    if params.has_key('q'):
	context_data['query'] = params['q']

    return render_to_response(template, context_data,
			      context_instance=RequestContext(request))

def ricerca_avanzata(request):
    return ricerca(edizioni_advanced_search, 
		   "biblioteca/ricerca_avanzata.html",
		   request)

def ricerca_rapida(request):
    return ricerca(edizioni_simple_search, 
		   "biblioteca/ricerca_rapida.html",
		   request)

templates/biblioteca/armadio.html
{% extends "biblioteca/layout.html" %}

{% block head %}
    <link rel='stylesheet' type='text/css' href='/static/css/app/armadio.css'>
{% endblock %}

{% block content %}

<h1>Vista armadio</h1>

<ul id='lista-armadi'>
    <li>{</li>

    {% for nome in armadi %}
        {% if nome == nome_armadio %}
        <li class='armadio corrente'>
        {% else %}
        <li class='armadio'>
        {% endif %}
            <a href='/armadi/{{ nome }}'>{{ nome }}</a>
        </li>
    {% endfor %}

    <li>}</li>
</ul>
<br>

{% if armadio %}

    {% for scaffale, copie in armadio.items %}
    <div class='scaffale'>
        <div class='scaffale-label'>
            <span>Scaffale</span>
            <span class='nome-scaffale'>{{ scaffale }}</span>
        </div>
        <div class='lista'>
            <ol>
            {% for posizione, copia in copie.items %}
                {% if not copia %}
                <li> - </li>
                {% else %}
                <li>
                    <a class='titolo'
                        href='/edizioni/{{ copia.edizione.id }}'
                        >{{ copia.edizione.titolo }}</a>

                    {% if copia.prestito_corrente %}
                        {% with copia.prestito_corrente as prestito %}
                        <a class='prestito'
                            href='/copie/{{ copia.id }}/+prestiti'>
                            In prestito a
                            <span class='nome'>
                                {{ prestito.nome }}
                                {{ prestito.cognome }}
                            </span>
                            dal
                            <span class='data'>{{ prestito.dataconsegna }}</span>
                        </a>
                        {% endwith %}
                    {% endif %}
                </li>
                {% endif %}

            {% endfor %}
            </ol>
        </div>
    </div>
    {% endfor %}
{% endif %}

{% endblock %}

templates/biblioteca/box_copia.html
<div class='box-copia'>
    <div class='locazione'>
        <div class='armadio'>
            {{ copia.armadio }}
        </div>
        <div class='scaffale'>
            {{ copia.scaffale }}
        </div>
        <div class='posizione'>
            {{ copia.posizione }}
        </div>
    </div>

    <div class='edizione'>
        <a class='titolo' href='/edizioni/{{copia.edizione.id}}'
            >{{ copia.edizione.titolo }}</a>
        <br>
        <span class='casaeditrice'>{{ copia.edizione.casaeditrice }}</span>
        -
        <span class='anno'>{{ copia.edizione.anno }}</span>
        {% if copia.edizione.isbn|length > 0 %}
        <br>
        <span class='isbn'>ISBN:{{ copia.edizione.isbn }}</span>
        {% endif %}

        {% if copia.note and copia.note|length > 0 %}
        <br>
        <div id='box-copia-{{ copia.id }}-note' class='note'>
            {{ copia.note|linebreaks }}
        </div>
        <a  href='#' class='note-toggle'
            onclick='$("#box-copia-{{ copia.id }}-note").toggle()'
            >Note &laquo;</a>
        {% endif %}
    </div>
</div>

templates/biblioteca/edizione_detail.html
{% extends "biblioteca/layout.html" %}

{% block head %}
    <link rel='stylesheet' type='text/css' href='/static/css/app/edizione_detail.css'>

    <script type='text/javascript'>

        $(function() {
            $("#confirm-delete").dialog(
                    { autoOpen: false
                    , modal: true
                    , title: "Conferma eliminazione"
                    , width: 650
                    , height: 200});
        });
    </script>
{% endblock %}

{% block content %}

<div id='info-edizione'>
    <a  class='btn primary' style='float: right'
        href='/edizioni/{{ edizione.id }}/modifica'
        >Modifica</a>
    <a  class='btn primary' id='delete'
        style='float: right' href='javascript:void(0)' 
        onclick='$("#confirm-delete").dialog("open")'
        >Elimina</a>


    <div class='titolo'> {{ edizione.titolo }} </div>

    <div class='autori'>
    {% if autori|length > 0 %}
        {% for autore in autori %}
            {% if forloop.counter > 1 %} - {% endif %}
            <a  class='autore'
                href='/ricerca?autore__nome={{ autore.nome|urlencode }}&autore__cognome={{ autore.cognome|urlencode }}'
                >{{ autore.nome }} {{ autore.cognome }}</a>
        {% endfor %}
    {% endif %}
    </div>

    <div class='info'>
        <a  href='/ricerca?casaeditrice={{ edizione.casaeditrice }}'
            ><span class='casaeditrice'
                >{{ edizione.casaeditrice }}</span></a>
        -
        <a href='/ricerca?anno={{ edizione.anno }}'
            ><span class='anno'>{{ edizione.anno }}</span></a>
        {% if edizione.isbn|length > 0 %}
            -
            <a href='/ricerca?isbn={{ edizione.isbn }}'>
                <span class='isbn'>ISBN:{{ edizione.isbn }}</span>
            </a>
        {% endif %}
    </div>
</div>

{% with edizione.copia_set.all as copie %}
<div style='width: 50%'>
    <h2>Copie</h2>

    {% if copie|length_is:"0" %}
        <div class='nessuna-copia'>
            Nessuna copia in archivio
            <br>
            <small>
                <a href='/edizioni/{{ edizione.id }}/modifica'>
                    Registra nuove copie nella pagina di modifica &raquo;
                </a>
            </small>
        </div>
    {% else %}

        <table id='tabella-copie'>

            {% for copia in copie %}
                <tbody>
                    <tr>
                        <td></td>
                        <td class='armadio'>
                            <a  href='/armadi/{{ copia.armadio }}'
                                >{{ copia.armadio }}</a>
                        </td>
                        <td class='scaffale'>{{ copia.scaffale }}</td>
                        <td class='posizione'>{{ copia.posizione }}</td>

                        <td class='stato-prestito'>
                            <a href='/copie/{{ copia.id }}/+prestiti'>
                                {% with copia.prestito_corrente as prestito %}
                                    {% if prestito %}
                                        In prestito a {{ prestito.nome }} {{ prestito.cognome }} &raquo;
                                    {% else %}
                                        Disponibile &raquo;
                                    {% endif %}
                                {% endwith %}
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td colspan='4' class='dataora'>
                            Aggiunta il {{ copia.dataora|date:"d/b/y, H:i" }}
                        </td>
                    </tr>
                    {% if copia.note %}
                        <tr>
                            <td></td>
                            <td colspan='4'>
                                <a class='note-link' href='#' onclick='$("#note-{{copia.id}}").toggle()'>Note &raquo;</a>
                                <div id='note-{{ copia.id }}' class='note' style='display: none'>
                                    {{ copia.note|linebreaks }}
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                </tbody>
        {% endfor %}
            
        </table>
    {% endif %}

</div>
{% endwith %}



<div id='confirm-delete' class='dialog'>
    <div id='question'>
        <img src='/static/img/warning.png' class='icon'>
        <div class='body'>
            <form method='post' action='/edizioni/{{ edizione.id }}/elimina' id='form-delete'>
                {% csrf_token %}
                <h1>Sei sicuro di voler eliminare questa edizione?</h1>
                <p>
                Verranno anche <b>eliminate le informazioni
                sulle copie</b> corrispondenti e i <b>relativi prestiti</b>.
                </p>
                <div class='commands'>
                    <a  class='btn primary' id='confirm'
                        href='javascript:void(0)'
                        onclick='$("#form-delete").submit()'
                        >Conferma</a>
                    <a  class='btn primary' id='cancel'
                            href='javascript:void(0)'
                            onclick='$("#confirm-delete").dialog("close")'
                            >Annulla</a>
                </div>
            </form>
        </div>
    </div>
</div>



{% endblock %}

templates/biblioteca/edizione_form.html
{% extends "biblioteca/layout.html" %}

{% block head %}
    <link rel='stylesheet' type='text/css' href='/static/css/app/edizione_form.css'>

    <script type='text/javascript' src='/static/js/jquery.formset.js'></script>
    <script type='text/javascript'>

        function toggleNote(pos) {
            var textarea = $("#id_copie-"+pos+"-note");

            if( textarea.attr('readonly') == false )
                textarea
                    .attr('readonly', 'true')
                    .addClass('readonly');
            else
                textarea
                    .attr('readonly', '')
                    .removeClass('readonly');
        }

        $(function() {
            $("#tabella-autori tbody tr").formset({
                 prefix:        '{{ formset_autori.prefix }}'
                ,formCssClass:  'dynamic-formset1'
                ,addText:       '<img src="/static/img/list-add.png"> Aggiungi'
                ,deleteText:    '<img src="/static/img/list-remove.png"> Rimuovi'
                ,added:         function(row) { $(row).find('.errors').remove(); }
            });
            $("#copie .copia").formset({
                 prefix:        '{{ formset_copie.prefix }}'
                ,formCssClass:  'dynamic-formset2'
                ,addText:       '<img src="/static/img/list-add.png"> Aggiungi'
                ,deleteText:    '<img src="/static/img/list-remove.png"> Rimuovi'
                ,added:         function(row) {
                                    $(row)
                                        .removeClass('invalid')
                                        .find('.errors').remove();
                                }
            });
        });
    </script>

{% endblock %}

{% block content %}
    <form   method='post' action='' id='main_form'>
    {% csrf_token %}

    <h1>
        <a  href='#' style='float: right'
            onclick='$("#main_form").submit()' class='btn primary'
            >Salva</a>
        {% if object %}
            Modifica edizione
            <a class='btn' style='float: right' href='/edizioni/{{ object.id }}'>Annulla</a>
        {% else %}
            Nuova edizione
            <a class='btn' style='float: right' href='/edizioni/aggiungi/googlebooks'>Importa da Google Books</a>
        {% endif %}
    </h1>


    <h2>Informazioni di base</h2>
    <table id='tabella-form-info' class='form-layout'>
        {% for row in form %}
            <tr>
                <th>{{ row.label }} &raquo;</th>
                <td>{{ row }}</td>
                {% if row.errors %}
                <td class='error-column'>
                    <div class='error popover'>
                        <div class='left arrow'></div>
                        <div class='content'>
                            {{ row.errors }}
                        </div>
                    </div>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>

    <div style='float: left; width: 40%; overflow: auto'>
        <h2>Autori</h2>
        <table id='tabella-autori'>
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Cognome</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for row in formset_autori %}
                <tr>
                    <td>{{ row.id }}
                        {% if row.instance.pk %}{{ row.DELETE }}{% endif %}
                        {{ row.nome }}</td>
                    <td>{{ row.cognome }}</td>
                    <td></td>
                </tr>

                {% if row.errors %}
                <tr class='errors'>
                    {% for column in row %}
                    <td>
                        {% if column.errors %}
                        <div class='error popover'>
                            <div class='top arrow'></div>
                            <div class='content'>
                                {{ column.errors }}
                            </div>
                        </div>
                        {% endif %}
                    </td>
                    {% endfor %}
                </tr>
                {% endif %}

                {% endfor %}
            </tbody>
        </table>
        {{ formset_autori.management_form }}
    </div>

    <div style='float: right; width: 55%; overflow: auto'>
        <h2>Copie</h2>

        <div id='copie'>
            {% for copia in formset_copie %}
                {% if copia.errors %}
                <div class='copia invalid'>
                {% else %}
                <div class='copia'>
                {% endif %}
                    {{ copia.id }}

                    <div class='number'>
                        {% if copia.instance.pk %}
                            {{ forloop.counter }}
                        {% else %}
                            *
                        {% endif %}
                    </div>

                    <div class='row-content'>
                        <div class='horiz'>
                            <div>Locazione &raquo;</div>
                            <div>{{ copia.armadio }}</div>
                            <div>{{ copia.scaffale }}</div>
                            <div>{{ copia.posizione }}</div>
                        </div>

                        <div class='horiz'>
                            <div>Note &raquo;</div>
                            {{ copia.note }}
                        </div>

                        {% if copia.instance.pk %}
                            <div class='dataora'>Aggiunta il {{ copia.instance.dataora }}</div>
                            {{ copia.DELETE }}
                        {% endif %}

                        {% if copia.errors %}
                            <div class='errors'>
                            {% for field, errors in copia.errors.items %}
                                <div class='field'>
                                    <div class='name'>{{ field|capfirst }}</div>
                                    {{ errors }}
                                </div> 
                                <script type='text/javascript'>
                                    $(function() {
                                        $("#id_{{ copia.prefix }}-{{ field }}")
                                            .addClass('invalid');
                                    });
                                </script>
                            {% endfor %}
                            </div> 
                        {% endif %}
                    </div>

                </div>
            {% endfor %}
        </div>
        {{ formset_copie.management_form }}
    </div>


    <div style='clear: both;'>
        <a  href='#' class='btn primary' style='float: right'
            onclick='$("#main_form").submit()'
            >Salva</a>
    </div>
    </form>
{% endblock %}